/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Management.java
 *
 * Created on Sep 24, 2014, 3:24:05 PM
 */

package Employee;

/**
 *
 * @author SONY
 */
public class Management extends javax.swing.JFrame {

    /** Creates new form Management */
    public Management() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("MANAGEMENT STAFF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 40, 300, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel8.setText("Mob. 9231225352");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 420, 150, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setText("DOB. 07/08/1975");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 400, 150, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel10.setText("avantika@gmail.com");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 440, 150, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel12.setText("Mrs. Avantika Patil");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 360, 160, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(667, 433, 0, 10);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel15.setText("Mr. Vaibhav Deshmukh");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 200, 150, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel16.setText("DOB. 19/05/1983");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(350, 240, 150, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel17.setText("Mob. 9821322122");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(350, 260, 150, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel18.setText("prasad@gmail.com");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(350, 280, 150, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel20.setText("Mr. Deepak Patel");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(690, 60, 150, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel21.setText("DOB. 12/02/1970");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(690, 100, 150, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel22.setText("Mob. 9821322122");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(690, 120, 150, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel23.setText("deepak@gmail.com");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(690, 140, 150, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 420, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     this.setVisible(false);
     mainFrame mm=new mainFrame();
     mm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
